name: Deploy Validator Site

on:
  push:
    paths:
      - 'docs/validator/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pyodide-build
        run: |
          pip install pyodide-build
          
      - name: Build Pyodide wheel
        run: |
          cd spotifyActionService/src/logic
          pyodide build
          cp dist/*.whl ../../../docs/validator/

      - name: Upload validator site
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/validator'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
