# .github/workflows/deploy_preview.yml
name: Deploy Validator Preview

on:
  pull_request:
    paths:
      - 'site/**'
      - 'actions.schema.json'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-preview-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy schema
        run: cp actions.schema.json site/

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages preview
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          preview: true
