# .github/workflows/deploy_preview.yml
name: Deploy Validator Preview

on:
  pull_request:
    paths:
      - 'docs/validator/**'
      - 'spotifyActionService/src/logic/**'
      - 'site/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-preview-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pyodide-build & setup Emscripten
        run: |
          pip install pyodide-build==0.30.5
          EMSDK_VER=3.1.46
          echo "EMSDK_VER=$EMSDK_VER" >> "$GITHUB_ENV"
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install $EMSDK_VER
          ./emsdk activate $EMSDK_VER
          source emsdk_env.sh
          cd ..

      - name: Build Pyodide wheel
        run: |
          cd spotifyActionService/src/logic
          pyodide build
          mkdir -p ../../../docs/validator
          cp dist/*.whl ../../../docs/validator/

      - name: Copy website assets
        run: |
          cp -r docs/validator/* docs/validator/

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/validator

      - name: Deploy to GitHub Pages preview
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          preview: true
